develop/config/routes.rb
Rails.application.routes.draw do

  get 'top' => 'top#top'
  delete 'top' => 'top#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations'
  }

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  namespace :admins do
    resources :orders, :users, :items, :artists, :genres, :discs, :songs, :labels
    end

  namespace :users do
    resources :carts, :items, :orders, :users, :cart_items, :addresses
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

develop/app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user, optional: true
end

develop/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

develop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

develop/app/models/artist.rb
class Artist < ApplicationRecord

	has_many :items, dependent: :destroy

end

develop/app/models/cart_item.rb
class CartItem < ApplicationRecord

	belongs_to :user
	belongs_to :item

	def items_price
		item.price * sheet
	end

	def  sub_total
		item.price.to_i * sheet.to_i
	end
	def sub_total_with_tax
		(sub_total.to_i * 1.08).round
	end


end

develop/app/models/disc.rb
class Disc < ApplicationRecord

	has_many :songs, :dependent => :destroy
	belongs_to :item
  accepts_nested_attributes_for :songs, allow_destroy: true
end

develop/app/models/genre.rb
class Genre < ApplicationRecord

	has_many :items, dependent: :destroy

end

develop/app/models/item.rb
class Item < ApplicationRecord

	acts_as_paranoid

	has_many :discs, :dependent => :destroy
	has_many :order_items, :dependent => :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true

	belongs_to :artist, optional: true
	belongs_to :label, optional: true
	belongs_to :genre, optional: true


    validate :add_error_sample

    def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if product_name.blank?
      errors[:base] << "商品名を入力してください"
    end

    # 価格が空のときにエラーメッセージを追加する
    if price.blank?
      errors[:base] << "価格を入力してください"
    end

    if stock_quantity.blank?
      errors[:base] << "在庫数を入力してください"
    end

  end
  def price_with_tax
    (price.to_i * 1.08).round
  end

	def self.search(search) #self.でクラスメソッドとしている
    	if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      		Item.where(['product_name LIKE ?', "%#{search}%"])
    	else
    		Item.all #全て表示。
    	end
	end



	enum sales_status:{
		販売中: 0,
		販売停止中: 1
	}
	attachment :jacket_image
end

develop/app/models/label.rb
class Label < ApplicationRecord

	has_many :items, dependent: :destroy

end

develop/app/models/order.rb
 class Order < ApplicationRecord

	has_many :order_items, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :order_items, allow_destroy: true

	enum payment_method: {
		銀行振込: 0,
		代金引換: 1,
		クレジットカード決済: 2
	}

	enum delivery_status: {
		受付: 0,
		商品準備中: 1,
		出荷済: 2
	}

   def name
     family_name + first_name
   end
end

develop/app/models/order_item.rb
class OrderItem < ApplicationRecord

	belongs_to :order
    belongs_to :item

    def subtotal
      price.to_i * sheet.to_i
    end


end

develop/app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc

end

develop/app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

	has_many :cart_items, dependent: :destroy
	has_many :orders, dependent: :destroy
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses, :cart_items

	enum is_deleted:{
		会員: 0,
		退会: 1
	}

	
	def self.search(search) #self.でクラスメソッドとしている
     if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       User.where(['family_name LIKE ? OR first_name LIKE ?', "%#{search}%" ,"%#{search}%"])
     else
       User.all #全て表示。
     end
    end

	def total_price
		cart_items = CartItem.where(user_id: id)
		cart_items.to_a.sum{|cart_item|cart_item.items_price}
	end

	def add_item(item_id)

		current_item = cart_items.find_by_item_id(item_id)

		if  current_item
			current_item.sheet += @current_item.sheet.to_i
		else
			current_item = cart_items.build(item_id: item_id)
		end
		current_item

	end



end

develop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

        before_action :set_header
        before_action :configure_permitted_parameters, if: :devise_controller?

	    protected

	    def configure_permitted_parameters
		  devise_parameter_sanitizer.permit(:sign_up, keys: [:address_id, :family_name, :first_name, :kana_family_name, :kana_first_name, :phone_number, :is_deleted])
	    end
	    
end

develop/app/controllers/top_controller.rb
class TopController < ApplicationController

  include DisplayUserHeader

  def top
  end

end

develop/app/helpers/application_helper.rb
module ApplicationHelper
end

develop/app/helpers/top_helper.rb
module TopHelper
end

develop/app/helpers/users/carts_helper.rb
module Users::CartsHelper
end

develop/app/helpers/users/items_helper.rb

module Users::ItemsHelper

  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end


end

develop/app/helpers/users_helper.rb
module UsersHelper
end

develop/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

develop/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

develop/app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <font color="#f5f5f5"><span>ECL</span></font>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li>
            <%= link_to "Items", admins_items_path, class: "glyphicon glyphicon-music" %>
          </li>
          <li>
            <%= link_to "Orders", admins_orders_path, class: "glyphicon glyphicon-list-alt" %>
          </li>
          <li>
            <%= link_to 'Users',admins_users_path, class: "glyphicon glyphicon-user" %>
          </li>
          <li>
            <%= link_to 'Add Item',new_admins_item_path, class: "glyphicon glyphicon-plus" %>
          </li>
          <li>
            <%= link_to "Logout", destroy_admin_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_admin_session_path, class: "glyphicon glyphicon-log-in" %>
          </li>
          <li>
            <%= link_to "Sign up", new_admin_registration_path, class: "glyphicon glyphicon-edit" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

develop/app/views/layouts/_user_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <font color="#f5f5f5"><span>ECL</span></font>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "ECL", top_path, class: "glyphicon glyphicon-home" %>
          </li>
          <li>
            <%= link_to "Items", users_items_path, class: "glyphicon glyphicon-music" %>
          </li>
          <li>
            <%= link_to "My page", users_user_path(current_user), class: "glyphicon glyphicon-user" %>
          </li>
          <li>
            <%= link_to "Cart", users_carts_path, class: "glyphicon glyphicon-shopping-cart" %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
          </li>
          <li>
            <font color="#f5f5f5">ようこそ<%= current_user.family_name %><%= current_user.first_name %>さん</font>
          </li>

        <% else %>
          <li>
            <%= link_to "ECL", top_path, class: "glyphicon glyphicon-home" %>
          </li>
          <li>
            <%= link_to 'Items', users_items_path, class: "glyphicon glyphicon-music" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
          </li>
          <li>
            <font color="#f5f5f5"> ようこそ　ゲスト さん</font>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

develop/app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
　　   <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <font color="#f5f5f5"><span>ECL</span></font>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Items", admins_items_path, class: "glyphicon glyphicon-music" %>
              </li>
              <li>
                <%= link_to "Orders", admins_orders_path, class: "glyphicon glyphicon-list-alt" %>
              </li>
              <li>
                <%= link_to 'Users',admins_users_path, class: "glyphicon glyphicon-user" %>
              </li>
              <li>
                <%= link_to 'Add Item',new_admins_item_path, class: "glyphicon glyphicon-plus" %>
              </li>
              <li>
                <%= link_to "Logout", destroy_admin_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Login", new_admin_session_path, class: "glyphicon glyphicon-log-in" %>
              </li>
              <li>
                <%= link_to "Sign up", new_admin_registration_path, class: "glyphicon glyphicon-edit" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% if flash[:notice] %>
      <div class=“flash”>
        <%= flash[:notice] %>
      </div>
    <% end %>
<br>
<br>
<br>
<br>
<br>
   <%= yield %>
  </body>
</html>

develop/app/views/layouts/another_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
　　   <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <span>ECL</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Items", admins_items_index_path, class: "glyphicon glyphicon-music" %>
              </li>
              <li>
                <%= link_to "Orders", admins_orders_index_path, class: "glyphicon glyphicon-list-alt" %>
              </li>
              <li>
                <%= link_to 'Users',admins_users_index_path, class: "glyphicon glyphicon-user" %>
              </li>
              <li>
                <%= link_to 'Add Item',admins_items_new_path, class: "glyphicon glyphicon-plus" %>
              </li>
              <li>
                <%= link_to "Logout", destroy_admin_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Login", new_admin_session_path, class: "glyphicon glyphicon-log-in" %>
              </li>
              <li>
                <%= link_to "Sign up", new_admin_registration_path, class: "glyphicon glyphicon-edit" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% if flash[:notice] %>
      <div class=“flash”>
        <%= flash[:notice] %>
      </div>
    <% end %>
<br>
<br>
<br>
<br>
<br>
   <%= yield %>
  </body>
</html>

develop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render @header %>

<br>
<br>
<br>
<br>
<br>
   <%= yield %>
  </body>
</html>