develop/config/routes.rb
Rails.application.routes.draw do

  get 'top' => 'top#top'
  delete 'top' => 'top#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations'
  }

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  namespace :admins do
    resources :orders, :users, :items, :artists, :genres, :discs, :songs, :labels
    end

  namespace :users do
    resources :carts, :items, :orders, :users, :cart_items, :addresses
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

develop/app/models/item.rb
class Item < ApplicationRecord

	acts_as_paranoid

	has_many :discs, :dependent => :destroy
	has_many :order_items, :dependent => :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true

	belongs_to :artist, optional: true
	belongs_to :label, optional: true
	belongs_to :genre, optional: true


    validate :add_error_sample

    def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if product_name.blank?
      errors[:base] << "商品名を入力してください"
    end

    # 価格が空のときにエラーメッセージを追加する
    if price.blank?
      errors[:base] << "価格を入力してください"
    end

    if stock_quantity.blank?
      errors[:base] << "在庫数を入力してください"
    end

  end
  def price_with_tax
    (price.to_i * 1.08).round
  end

	def self.search(search) #self.でクラスメソッドとしている
    	if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      		Item.where(['product_name LIKE ?', "%#{search}%"])
    	else
    		Item.all #全て表示。
    	end
	end



	enum sales_status:{
		販売中: 0,
		販売停止中: 1
	}
	attachment :jacket_image
end

develop/app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

	has_many :cart_items, dependent: :destroy
	has_many :orders, dependent: :destroy
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses, :cart_items

	enum is_deleted:{
		会員: 0,
		退会: 1
	}

	
	def self.search(search) #self.でクラスメソッドとしている
     if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       User.where(['family_name LIKE ? OR first_name LIKE ?', "%#{search}%" ,"%#{search}%"])
     else
       User.all #全て表示。
     end
    end

	def total_price
		cart_items = CartItem.where(user_id: id)
		cart_items.to_a.sum{|cart_item|cart_item.items_price}
	end

	def add_item(item_id)

		current_item = cart_items.find_by_item_id(item_id)

		if  current_item
			current_item.sheet += @current_item.sheet.to_i
		else
			current_item = cart_items.build(item_id: item_id)
		end
		current_item

	end



end

develop/app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

before_action :authenticate_admin!

  include DisplayAdminHeader

  def index
    @items = Item.page(params[:page]).per(20).search(params[:search]).order(id: "DESC")
  end

  def show
    @item = Item.find(params[:id])
    @discs = @item.discs
  end

  def new
    @item = Item.new
    @disc = @item.discs.build
    @songs = @disc.songs.build

  end

  def create
    @item = Item.new(item_params)
      if @item.save
        redirect_to admins_items_path
        flash[:notice] = "成功しました"
      else
        render:new
      end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_path
      flash[:notice] = "成功しました"
    else
      render:show
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admins_items_path
  end

  private

  def item_params
    params.require(:item).permit(:product_name, :price, :artist_id, :genre_id, :label_id, :jacket_image, :remove_jacket_image, :stock_quantity, :sales_status, discs_attributes: [:id, :disc_name, :_destroy, songs_attributes: [:id, :song_name, :song_turn, :_destroy]])
  end
end

develop/app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  before_action :authenticate_admin!

  include DisplayAdminHeader

  def index

    @user = User.all
    #@user = User.find
    #@user = User.search(params[:search])
    @user = User.page(params[:page]).per(20).search(params[:search]).order(id: "DESC")

    #@users = User.page(params[:page]).per(20)

  end

  def show
    @user = User.find(params[:id])
    #@address = Address.find_by(post_number: params[:post_number],address: params[:address])
    #@address = @user.addresses.all
    @orders = @user.orders.page(params[:page]).per(3).order(id: "DESC")
    #@orders = Order.page(params[:page]).per(3)
  end

  def edit
    @user = User.find(params[:id])
    @user.addresses.build
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_user_path(@user.id)
    else
      end
  end

  def destroy
    @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = "退会させました"
      redirect_to admins_users_path
 end

  private

   def user_params
  params.require(:user).permit(:email,:encrypted_password,:address_id, :family_name,:firstname,:kana_family_name,:kana_first_name,:phone_number,
                                address_attributes:[:id,:post_number,:address])
end

end

develop/app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController

  include DisplayUserHeader

  def new
    @address = Address.new
  end

  def edit
    @address = Address.where(user_id: current_user.id)
  end

  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    @address.save
    if @address == current_user.addresses.first
      redirect_to users_items_path
    else
      redirect_to edit_users_user_path(current_user)
    end
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = "変更しました"
    redirect_to edit_users_user_path(current_user)
  else
   
  end

  end
  def destroy

    @address = Address.find(params[:id])
    if @address.destroy
      flash[:notice] = "削除しました"
    redirect_to edit_users_user_path(current_user)
  end
    
  end

  private
  def address_params
    params.require(:address).permit(:id, :user_id, :family_name, :first_name, :kana_family_name, :kana_first_name, :post_number, :address, :phone_number)
  end
end

develop/app/controllers/users/cart_items_controller.rb
 # include DisplayUserHeader ヘッダーを読み込むコード

develop/app/controllers/users/carts_controller.rb
class Users::CartsController < ApplicationController

  before_action :authenticate_user!

  include DisplayUserHeader

  def index
    @user = current_user
  	@cart_items = CartItem.all
    @item = Item
  end

    def show
      @user = current_user

     @cart_item = CartItem.find(params[:id])
end


def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.save
    if @cart_item.item.stock_quantity.to_i >= @cart_item.sheet.to_i
    redirect_to users_carts_path
    else
    @cart_item.destroy
    redirect_to users_carts_path
    flash[:notice] = "在庫より注文数量が多い商品があります"
  end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    if @cart_item.item.stock_quantity.to_i >= @cart_item.sheet.to_i
    redirect_to users_carts_path
    else
    @cart_item.destroy
    redirect_to users_carts_path
    flash[:notice] = "在庫より注文数量が多い商品があります"

  end
end

  def destroy
  	@cart_item = CartItem.find(params[:id])
  	@cart_item.destroy
  	redirect_to users_carts_path
  end

def add_item(item_id)

    current_item = @user.cart_items.find_by_item_id(item_id)

    if  current_item
          current_item.update(cart_item_params)


    else
      current_item = @user.cart_items.build(cart_item_params)
      @cart_item.save
    end

  end




  private
  def cart_item_params
    params.require(:cart_item).permit(:id, :user_id, :item_id, :sheet)
  end
end

develop/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController

  include DisplayUserHeader

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

develop/app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController

  include DisplayUserHeader

  def index
    @items = Item.page(params[:page]).per(30).search(params[:search]).order(id: "DESC")
    #@count = Item.search
   end


def show
    @item = Item.find(params[:id])
    @discs = @item.discs.all
    @user = current_user
    if user_signed_in?
      @cart_items = @user.cart_items
      @current_item = @user.cart_items.find_by(item_id: @item.id)

      if  @current_item
        @cart_item = CartItem.find(@current_item.id)
      else
        @cart_item = CartItem.new
      end
    end
  end




  private
  def item_params
    params.require(:item).permit(:product_name, :price, :jacket_image, :remove_jacket_image, :stock_quantity, :sales_status, discs_attributes: [:id, :disc_name, :_destroy,
                                                         songs_attributes: [:id, :song_name, :song_turn, :_destroy]])
  end

end

develop/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

develop/app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController

  include DisplayUserHeader



  def new

    @user = current_user
    @addresses = @user.addresses.all
    @current_address = @user.addresses.first
    if @current_address
    @order = Order.new
    @order_items = @order.order_items.build
    @user = current_user
    else
    redirect_to new_users_address_path
  end
  end


  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @cart_items = CartItem.where(user_id: current_user.id)
    @cart_items.each do |cart_item|
      @item = cart_item.item
      if @item.stock_quantity >= cart_item.sheet
        @item.decrement!(:stock_quantity, cart_item.sheet.to_i)
        cart_item.destroy
      else
        redirect_to users_carts_path
      end
    end
      @order.delivery_status = 0
      @ad_info = Address.find_by(address: @order.address)
      @order.post_number = @ad_info.post_number
      @order.family_name = @ad_info.family_name
      @order.first_name = @ad_info.first_name
      @order.phone_number = @ad_info.phone_number
      @order.save
      flash[:notice] = "購入ありがとうございました。カートは空です。"
      redirect_to users_user_path(current_user)
  end


private
 def order_params
    params.require(:order).permit(:user_id, :payment_method, :delivery_status, :address, :post_number, :family_name, :first_name, :phone_number, :total_price, :shipping_fee,
    :amount, order_items_attributes: [:id, :item_id, :sheet, :price, :_destroy])
end

end

develop/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController

  include DisplayUserHeader

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

develop/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  include DisplayUserHeader

  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :phone_number])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_users_address_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

develop/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  include DisplayUserHeader

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  def after_sign_in_path_for(resource)
          users_items_path
   
    end


  def after_sign_out_path_for(resource)
    top_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

develop/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController

  include DisplayUserHeader

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

develop/app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

  include DisplayUserHeader

  def show
    @user = current_user
    @current_address = @user.addresses.first
    if @current_address #@user.ddresses.present?

      @orders = Order.where(user_id: current_user.id).page(params[:page]).per(3).order(id: "DESC")
      @items = Item.all#
    else
        redirect_to new_users_address_path
    end

  end

  def edit
    @user = User.find(params[:id])
   @user.addresses.build #意味は？
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:encrypted_password].blank?
      params[:user].delete("encrypted_password")
    end
     @user.update(user_params)
     redirect_to users_items_path
  
  end


  

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/top'
     flash[:notice] = "退会しました"
  end



  private
  def user_params
  params.require(:user).permit(:email,:encrypted_password,:address_id, :family_name,:firstname,:kana_family_name,:kana_first_name,:phone_number　)
  end
  def address_params
    params.require(:address).permit(:post_number,:address)
  end

end

develop/app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

develop/app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

develop/app/helpers/users/addresses_helper.rb
module Users::AddressesHelper
end

develop/app/helpers/users/carts_helper.rb
module Users::CartsHelper
end

develop/app/views/users/items/aaa.html.erb
<body data-page="products:index" id="comable-product">
  <div id="awesome_admin_layout">
  <main class="awesome_admin_layout-main">
    <div id="wrapper" class=" ">
      <main class="container-fluid">
        <div class="comable-page">
          <div class="comable-page-heading">
            <ul class="pull-right list-inline">
              <li><a href="/"></a><a class="btn btn-default" href="/admins/items/new">新規作成</a></li>
            </ul>
            <h1 class="page-header">商品管理 <small><%= @items.count %> 件</small></h1>
          </div>
          <div class="comable-page-body">
            <div class="comable-search">
              <%= form_tag users_items_path, :method => 'get' do %>
              <p><%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :product_name => nil %></p>
              <% end %>
            </div>
          <section>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th></th>
                  <th><a class="sort_link">商品コード</a></th>
                  <th><a class="sort_link">商品名</a></th>
                  <th><a class="sort_link">アーティスト名</a></th>
                  <th><a class="sort_link">価格</a></th>
                  <th>在庫</th>
                </tr>
              </thead>
              <tbody>
                <% @items.each do |item| %>
                <tr>
                  <td class="comable-image"><%= link_to admins_item_path(item.id), class: "thumbnail" do %><%= attachment_image_tag item, :jacket_image, :fill, 100, 100, format: 'jpeg', fallback:"no_image.jpg" %><% end %></td>
                  <td><%= link_to admins_item_path(item.id) do %><%= item.id %><% end %></td>
                  <td><%= item.product_name %></td>
                  <td><% if item.artist.present? %><%= item.artist.artist_name %><% end %></td>
                  <td><%= item.price %>円</td>
                  <td>
                    <ul class="list-unstyled">
                      <li><strong class="text-success"><%= item.stock_quantity %></strong></li>
                    </ul>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <div class="text-center"><%= paginate @items %></div>
          </section>
        </div>
    </div>
    </main>
    </div>
  </main>
  </div>
</body>

develop/app/views/users/items/index.html.erb
<% if flash[:notice] %>
  <div id="gritter-notice-wrapper">
    <div id="gritter-item-1" class="gritter-item-wrapper">
      <div class="gritter-item gritter-css3">
        <div class="gritter-close" style="display: none;"></div><img src="/assets/1249.png" class="gritter-image">
        <div class="gritter-with-image">
          <span class="gritter-title">Notification</span>
          <p><%= flash[:notice] %></p></div>
          <div style="clear:both"></div></div></div></div><% end %>


<div id="wrap">
    <main class="container">
      <div id="main">
        <ul class="breadcrumb">
          <li><a href="/users/items">商品一覧</a></li>
        </ul>
        <hr class="line-bg">
        <p class="result">商品数：<%= @items.count %></p>
        <div class="search">
        <%= form_tag users_items_path, :method => 'get' do %>
          <p><%= text_field_tag :search, params[:search] %>
             <%= submit_tag "Search", :product_name => nil %></p>
        <% end %>
        </div>
        <div id="per_page">
        <p class="cate"><%= paginate @items %></p>
        </div>
        <div class="product col-sm-10">
          <ul class="product">
            <% @items.each do |item| %>
            <li class="col-sm-4"><%= link_to users_item_path(item.id), class: "thumbnail" do %><%= attachment_image_tag item, :jacket_image, :fill, 100, 100, format: 'jpeg', fallback:"no_image.jpg" %><% end %>
              <div
                class="name"><%= link_to users_item_path(item.id) do %><%= item.product_name %><% end %></div>
              <div
                class="name"><% if item.artist.present? %><%= item.artist.artist_name %><% end %></div>
        <div class="price">税込: <%= number_with_delimiter(item.price_with_tax.to_s) %>円</div>
        <% if item.stock_quantity == 0 %><font color="red"><h4><売り切れ></h4></font><% end %>
        </li>
        <% end %>
  </ul>
  </div>
  </div>
  </main>
  </div>

<script>
  $(function(){
  setTimeout("$('.gritter-item').fadeOut('slow')", 3000)
})
</script>

develop/app/views/users/items/show.html.erb
  <div id="wrap">
    <main class="container">
      <div id="contents">
        <div id="main">
          <ul class="breadcrumb">
            <li><a href="/users/items">商品一覧</a></li>
            <li class="active"><span>&gt;　</span><%= @item.product_name %></li>
          </ul>
          <hr class="line-bg">
          <div id="ProductDetailArea">
            <div class="main-product">
              <div class="sample"><%= attachment_image_tag @item, :jacket_image, :fill, 150, 150, format: 'jpeg', fallback:"no_image.jpg" %></div>
              <ul class="stock">
                <% if user_signed_in? %>
                <% if @cart_item.sheet.present? %>
                    <li class="ed"><div class="sold_out">この商品は現在<%= @cart_item.sheet %>枚カートに入っています。</div></li>
                    <%= form_for(@cart_item, url: users_cart_path(@cart_item)) do |f| %>
                    <li class="ed">
                    <p>在庫数</p>
                    <p>（<%= @item.stock_quantity %>）</p>
                    <div class="add_cart form-inline form-group">
                    <% if user_signed_in? %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :item_id, value: @item.id %>
                    <%= f.number_field :sheet, in:1..10 %> 枚
                    <%= f.submit "数量を変更する" %>
                    <% else %>
                    <%= link_to "カートに入れる", new_user_session_path %>
                    <% end %>
                    </div>
                    </li>
                <% end %>
              </ul>
            </div>
                    <% else %>
                    <%= form_for(@cart_item, url: users_carts_path) do |f| %>
                    <li class="ed">
                    <p>在庫数 （<%= @item.stock_quantity %>）</p>
                    <div class="add_cart form-inline form-group">

                    <% if user_signed_in? %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :item_id, value: @item.id %>
                    <%= f.number_field :sheet, in:1..10 %> 枚<br>
                    <%= f.submit "カートに入れる" %>
                    <% else %>
                    <%= link_to "カートに入れる", new_user_session_path %>
                    <% end %>
                    </div>
                    </li>
                    <% end %>
              </ul>
            </div>
                 <% end %>
                 <% end %>


            <!--詳細側-->
            <div class="main-detail">
              <% if @item.stock_quantity == 0 %><font color="red"><h3><売り切れ></h3></font><% end %>
              <p class="lot-number">商品番号：<%= @item.id %></p>
              <h1><%= @item.product_name %></h1>
              <h1><% if @item.artist.present? %><%= @item.artist.artist_name %><% end %></h1>
              <h2>税込: <%= number_with_delimiter(@item.price_with_tax.to_s) %> 円</h2>
            </div>
            <div class="introduction">
              商品詳細 <br><br>
              アーティスト：<% if @item.artist.present? %><%= @item.artist.artist_name %><% end %><br><br>
              ジャンル：<% if @item.genre.present? %><%= @item.genre.genre_name %><% end %><br><br>
              レーベル：<% if @item.label.present? %><%= @item.label.label_name %><% end %><br><br>
              <% sum = 1 %><% @item.discs.each do |discs| %>
              ディスク<%= sum %><br><% summer = 1 %><% discs.songs.each do |songs| %><%= summer %>． <%= songs.song_name %><% summer += 1 %><br><% end %><% sum += 1 %><br><% end %>
            </div>
            <hr class="dod">
          </div>

        </div>
      </div>
    </main>
  </div>