develop/config/routes.rb
Rails.application.routes.draw do

  get 'top' => 'top#top'
  delete 'top' => 'top#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations'
  }

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  namespace :admins do
    resources :orders, :users, :items, :artists, :genres, :discs, :songs, :labels
    end

  namespace :users do
    resources :carts, :items, :orders, :users, :cart_items, :addresses
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

develop/app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

	has_many :cart_items, dependent: :destroy
	has_many :orders, dependent: :destroy
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses, :cart_items

	enum is_deleted:{
		会員: 0,
		退会: 1
	}

	
	def self.search(search) #self.でクラスメソッドとしている
     if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       User.where(['family_name LIKE ? OR first_name LIKE ?', "%#{search}%" ,"%#{search}%"])
     else
       User.all #全て表示。
     end
    end

	def total_price
		cart_items = CartItem.where(user_id: id)
		cart_items.to_a.sum{|cart_item|cart_item.items_price}
	end

	def add_item(item_id)

		current_item = cart_items.find_by_item_id(item_id)

		if  current_item
			current_item.sheet += @current_item.sheet.to_i
		else
			current_item = cart_items.build(item_id: item_id)
		end
		current_item

	end



end

develop/app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  before_action :authenticate_admin!

  include DisplayAdminHeader

  def index

    @user = User.all
    #@user = User.find
    #@user = User.search(params[:search])
    @user = User.page(params[:page]).per(20).search(params[:search]).order(id: "DESC")

    #@users = User.page(params[:page]).per(20)

  end

  def show
    @user = User.find(params[:id])
    #@address = Address.find_by(post_number: params[:post_number],address: params[:address])
    #@address = @user.addresses.all
    @orders = @user.orders.page(params[:page]).per(3).order(id: "DESC")
    #@orders = Order.page(params[:page]).per(3)
  end

  def edit
    @user = User.find(params[:id])
    @user.addresses.build
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_user_path(@user.id)
    else
      end
  end

  def destroy
    @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = "退会させました"
      redirect_to admins_users_path
 end

  private

   def user_params
  params.require(:user).permit(:email,:encrypted_password,:address_id, :family_name,:firstname,:kana_family_name,:kana_first_name,:phone_number,
                                address_attributes:[:id,:post_number,:address])
end

end

develop/app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController

  include DisplayUserHeader

  def new
    @address = Address.new
  end

  def edit
    @address = Address.where(user_id: current_user.id)
  end

  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    @address.save
    if @address == current_user.addresses.first
      redirect_to users_items_path
    else
      redirect_to edit_users_user_path(current_user)
    end
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = "変更しました"
    redirect_to edit_users_user_path(current_user)
  else
   
  end

  end
  def destroy

    @address = Address.find(params[:id])
    if @address.destroy
      flash[:notice] = "削除しました"
    redirect_to edit_users_user_path(current_user)
  end
    
  end

  private
  def address_params
    params.require(:address).permit(:id, :user_id, :family_name, :first_name, :kana_family_name, :kana_first_name, :post_number, :address, :phone_number)
  end
end

develop/app/controllers/users/cart_items_controller.rb
 # include DisplayUserHeader ヘッダーを読み込むコード

develop/app/controllers/users/carts_controller.rb
class Users::CartsController < ApplicationController

  before_action :authenticate_user!

  include DisplayUserHeader

  def index
    @user = current_user
  	@cart_items = CartItem.all
    @item = Item
  end

    def show
      @user = current_user

     @cart_item = CartItem.find(params[:id])
end


def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.save
    if @cart_item.item.stock_quantity.to_i >= @cart_item.sheet.to_i
    redirect_to users_carts_path
    else
    @cart_item.destroy
    redirect_to users_carts_path
    flash[:notice] = "在庫より注文数量が多い商品があります"
  end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    if @cart_item.item.stock_quantity.to_i >= @cart_item.sheet.to_i
    redirect_to users_carts_path
    else
    @cart_item.destroy
    redirect_to users_carts_path
    flash[:notice] = "在庫より注文数量が多い商品があります"

  end
end

  def destroy
  	@cart_item = CartItem.find(params[:id])
  	@cart_item.destroy
  	redirect_to users_carts_path
  end

def add_item(item_id)

    current_item = @user.cart_items.find_by_item_id(item_id)

    if  current_item
          current_item.update(cart_item_params)


    else
      current_item = @user.cart_items.build(cart_item_params)
      @cart_item.save
    end

  end




  private
  def cart_item_params
    params.require(:cart_item).permit(:id, :user_id, :item_id, :sheet)
  end
end

develop/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController

  include DisplayUserHeader

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

develop/app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController

  include DisplayUserHeader

  def index
    @items = Item.page(params[:page]).per(30).search(params[:search]).order(id: "DESC")
    #@count = Item.search
   end


def show
    @item = Item.find(params[:id])
    @discs = @item.discs.all
    @user = current_user
    if user_signed_in?
      @cart_items = @user.cart_items
      @current_item = @user.cart_items.find_by(item_id: @item.id)

      if  @current_item
        @cart_item = CartItem.find(@current_item.id)
      else
        @cart_item = CartItem.new
      end
    end
  end




  private
  def item_params
    params.require(:item).permit(:product_name, :price, :jacket_image, :remove_jacket_image, :stock_quantity, :sales_status, discs_attributes: [:id, :disc_name, :_destroy,
                                                         songs_attributes: [:id, :song_name, :song_turn, :_destroy]])
  end

end

develop/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

develop/app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController

  include DisplayUserHeader



  def new

    @user = current_user
    @addresses = @user.addresses.all
    @current_address = @user.addresses.first
    if @current_address
    @order = Order.new
    @order_items = @order.order_items.build
    @user = current_user
    else
    redirect_to new_users_address_path
  end
  end


  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @cart_items = CartItem.where(user_id: current_user.id)
    @cart_items.each do |cart_item|
      @item = cart_item.item
      if @item.stock_quantity >= cart_item.sheet
        @item.decrement!(:stock_quantity, cart_item.sheet.to_i)
        cart_item.destroy
      else
        redirect_to users_carts_path
      end
    end
      @order.delivery_status = 0
      @ad_info = Address.find_by(address: @order.address)
      @order.post_number = @ad_info.post_number
      @order.family_name = @ad_info.family_name
      @order.first_name = @ad_info.first_name
      @order.phone_number = @ad_info.phone_number
      @order.save
      flash[:notice] = "購入ありがとうございました。カートは空です。"
      redirect_to users_user_path(current_user)
  end


private
 def order_params
    params.require(:order).permit(:user_id, :payment_method, :delivery_status, :address, :post_number, :family_name, :first_name, :phone_number, :total_price, :shipping_fee,
    :amount, order_items_attributes: [:id, :item_id, :sheet, :price, :_destroy])
end

end

develop/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController

  include DisplayUserHeader

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

develop/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  include DisplayUserHeader

  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :phone_number])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_users_address_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

develop/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  include DisplayUserHeader

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  def after_sign_in_path_for(resource)
          users_items_path
   
    end


  def after_sign_out_path_for(resource)
    top_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

develop/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController

  include DisplayUserHeader

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

develop/app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

  include DisplayUserHeader

  def show
    @user = current_user
    @current_address = @user.addresses.first
    if @current_address #@user.ddresses.present?

      @orders = Order.where(user_id: current_user.id).page(params[:page]).per(3).order(id: "DESC")
      @items = Item.all#
    else
        redirect_to new_users_address_path
    end

  end

  def edit
    @user = User.find(params[:id])
   @user.addresses.build #意味は？
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:encrypted_password].blank?
      params[:user].delete("encrypted_password")
    end
     @user.update(user_params)
     redirect_to users_items_path
  
  end


  

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/top'
     flash[:notice] = "退会しました"
  end



  private
  def user_params
  params.require(:user).permit(:email,:encrypted_password,:address_id, :family_name,:firstname,:kana_family_name,:kana_first_name,:phone_number　)
  end
  def address_params
    params.require(:address).permit(:post_number,:address)
  end

end

develop/app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

develop/app/helpers/users/addresses_helper.rb
module Users::AddressesHelper
end

develop/app/helpers/users/carts_helper.rb
module Users::CartsHelper
end

develop/app/helpers/users/items_helper.rb

module Users::ItemsHelper

  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end


end

develop/app/helpers/users/orders_helper.rb
module Users::OrdersHelper
end

develop/app/helpers/users/users_helper.rb
module Users::UsersHelper
end

develop/app/views/admins/users/destroy.html.erb
<h1>Admins::Users#destroy</h1>
<p>Find me in app/views/admins/users/destroy.html.erb</p>

develop/app/views/admins/users/edit.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<h2>ECL</h2>
			  <tbody>

			  	<thead>ユーザー情報編集</thead>

				<%= form_for @user,:url => {:action => :update} do |f| %>
				<table>
				<tr>
				<div class="form-group has-icon">
					  <%= f.label :family_name, "姓" %><br>
					  <%= f.text_field :family_name, class: "family_name", autofocus: true, autocomplete: "family_name" %>
				</div>
				  <div>
				  	  <%= f.label :first_name, "名" %><br>
				  	  <%= f.text_field :first_name, class: "first_name", autocomplete: "first_name" %>
				  </div>
			    </tr>
			    <tr>
			    	<div>
			    	  <%= f.label :kana_family_name, "セイ" %><br>
			    	  <%= f.text_field :kana_family_name, class: "kana_family_name", autocomplete: "kana_family_name" %>
			        </div>
			        <div>
			          <%= f.label :kana_first_name, "メイ" %><br>
			          <%= f.text_field :kana_first_name, class: "kana_first_name", autocomplete: "kana_first_name" %>
			        </div>
			    </tr>
			    <tr>
			    	<div>
			    		<%= f.label "登録済み住所" %><br>
			    		<%= link_to "住所の編集と削除",edit_users_address_path,class: "col-lg-3 btn btn-default" %><br>
			    		<br>
			    		<div>
			    			<% @user.addresses.each do |address| %>
			    			<%= address.post_number %><br>
			    			<%= address.address %><br><br><br>
			    			<% end %>
		    			</div>
		    		</div>
			    </tr>
			    <tr>
			    	<div>
			    		<%= f.label :phene_number, "電話番号（ハイフンなし）" %><br>
			    		<%= f.text_field :phone_number, class: "phone_number", autocomplete: "phone_number" %>
			    	</div>
			    </tr>
			    <tr>
			    	<div>
			    		<%= f.label :email, "メールアドレス" %><br>
			    		<%= f.email_field :email, class: "email", autocomplete: "email" %>
			    	</div>
			    </tr>
			         <div class="actions">
			         	<%= f.submit "編集する" %>
			         </div>
				<% end %>
				<%= link_to "退会させる", users_user_path(@user), method: :delete, class:"btn btn-danger" %>
			</table>
			  </tbody>
			</div>
		</div>
</div>

develop/app/views/admins/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
    <h2>Users</h2>
      <div id="nav-search">
        <%= form_tag admins_users_path, :method => 'get' do %>
            <p class="text-right">
                <%= text_field_tag :search, params[:search] %>

                <%= submit_tag "検索", :name  => nil %>


            </p>
             <% end %>
       
      </div>
    </div>

    <div class="col-xs-12">
      <table class="table table-striped">
        <thead>
         <tr>
          <th>Name</th>
          <th>Phone_Number</th>
          <th>E-mail</th>
          <th></th>
         <tr>
        </thead>

        
        

        <% @user.each do |user| %>
        <tbody>
          <tr>
            <td><%= link_to admins_user_path(user.id) do %>
              <%= user.family_name %><%= user.first_name %>
                <% end %>
            </td>
            <td><%= user.phone_number %></td>

            <td><%= user.email %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
     <%= paginate @user %>
    </div>
  </div>
</div>

develop/app/views/admins/users/show.html.erb
<div class="container">

    <div class="row">

      <div class="col-lg-3">
        <table class="table table-stryped">
          <thead>
             <h2>User info</h2>
          </thead>

            <tbody>
            <tr>
              <td>
                <%= @user.kana_family_name %>
                <%= @user.kana_first_name %>
              </td>
            </tr>
            <tr>
              <td>
                <%= @user.family_name %>
                <%= @user.first_name %>
              </td>
            </tr>
            <tr>
              <td>
                <% @user.addresses.each do |address| %>
                〒<%= address.post_number %><br>
                <%= address.address %><br><br>
                <% end %>
              </td>
            </tr>
          </div>
            <tr>
              <td><%= @user.phone_number %></td>
            </tr>
            <tr>
              <td><%= @user.email %></td>
            </tr>
            <tr>

              <td><%= link_to "編集", edit_admins_user_path(@user.id), class: "col-lg-6 btn btn-default" %></td>
            </tr>
           </tbody>
        </table>


      </div>
      <div class="col-lg-9">
        <table class="table table-stryped">
          <thead>
            <h2>受注履歴</h2>
          </thead>

          <tbody>

            <% @orders.each do |order| %>
<tr>
              <th>
                <%= link_to admins_order_path(order.id) do %>
                <%= order[:created_at].strftime("%Y-%m-%d　%H:%M")  %>
                <% end %>
              </th>
              <th>
                <%= order.delivery_status %>
              </th>
            </tr>
            <tr>
              <td>
               配送先<br>
               〒<%= order.post_number %><br>
                <%= order.address %>
              </td>
              <td>支払い:<%= order.payment_method %><br>
                合計金額(税込　送料別):￥ <%= number_with_delimiter(order.total_price.round).to_s %><br>
                別途送料:￥ <%= order.shipping_fee %><br>
                請求額(税、送料込):￥<%= number_with_delimiter(order.amount.round).to_s %>円
              </td>
            </tr>
            <tr>
                <% order.order_items.each do |order_item| %>
              <td>
                <%= link_to admins_item_path(order_item.item.id) do %>
                <%= order_item.item.product_name  %>
                <% end %>
              </td>

              <% sub_total = ((order_item.price.to_i * order_item.sheet.to_i)*1.08).round %>
               <td>
                 <%= number_with_delimiter((order_item.price*1.08).round).to_s%> × <%= order_item.sheet %> = <%= number_with_delimiter((order_item.price*1.08*order_item.sheet).round).to_s %>(税込)<br>
                
              </td>
            </tr>

           <% end %>
                       <tr><td><td><br><br></td></td></tr>
           <% end %>
            <%= paginate @orders %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

develop/app/views/admins/users/update.html.erb
<h1>Admins::Users#update</h1>
<p>Find me in app/views/admins/users/update.html.erb</p>