develop/config/routes.rb
Rails.application.routes.draw do

  get 'top' => 'top#top'
  delete 'top' => 'top#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations'
  }

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  namespace :admins do
    resources :orders, :users, :items, :artists, :genres, :discs, :songs, :labels
    end

  namespace :users do
    resources :carts, :items, :orders, :users, :cart_items, :addresses
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

develop/app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user, optional: true
end

develop/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

develop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

develop/app/models/artist.rb
class Artist < ApplicationRecord

	has_many :items, dependent: :destroy

end

develop/app/models/cart_item.rb
class CartItem < ApplicationRecord

	belongs_to :user
	belongs_to :item

	def items_price
		item.price * sheet
	end

	def  sub_total
		item.price.to_i * sheet.to_i
	end
	def sub_total_with_tax
		(sub_total.to_i * 1.08).round
	end


end

develop/app/models/disc.rb
class Disc < ApplicationRecord

	has_many :songs, :dependent => :destroy
	belongs_to :item
  accepts_nested_attributes_for :songs, allow_destroy: true
end

develop/app/models/genre.rb
class Genre < ApplicationRecord

	has_many :items, dependent: :destroy

end

develop/app/models/item.rb
class Item < ApplicationRecord

	acts_as_paranoid

	has_many :discs, :dependent => :destroy
	has_many :order_items, :dependent => :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true

	belongs_to :artist, optional: true
	belongs_to :label, optional: true
	belongs_to :genre, optional: true


    validate :add_error_sample

    def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if product_name.blank?
      errors[:base] << "商品名を入力してください"
    end

    # 価格が空のときにエラーメッセージを追加する
    if price.blank?
      errors[:base] << "価格を入力してください"
    end

    if stock_quantity.blank?
      errors[:base] << "在庫数を入力してください"
    end

  end
  def price_with_tax
    (price.to_i * 1.08).round
  end

	def self.search(search) #self.でクラスメソッドとしている
    	if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      		Item.where(['product_name LIKE ?', "%#{search}%"])
    	else
    		Item.all #全て表示。
    	end
	end



	enum sales_status:{
		販売中: 0,
		販売停止中: 1
	}
	attachment :jacket_image
end

develop/app/models/label.rb
class Label < ApplicationRecord

	has_many :items, dependent: :destroy

end

develop/app/models/order.rb
 class Order < ApplicationRecord

	has_many :order_items, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :order_items, allow_destroy: true

	enum payment_method: {
		銀行振込: 0,
		代金引換: 1,
		クレジットカード決済: 2
	}

	enum delivery_status: {
		受付: 0,
		商品準備中: 1,
		出荷済: 2
	}

   def name
     family_name + first_name
   end
end

develop/app/models/order_item.rb
class OrderItem < ApplicationRecord

	belongs_to :order
    belongs_to :item

    def subtotal
      price.to_i * sheet.to_i
    end


end

develop/app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc

end

develop/app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

	has_many :cart_items, dependent: :destroy
	has_many :orders, dependent: :destroy
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses, :cart_items

	enum is_deleted:{
		会員: 0,
		退会: 1
	}

	
	def self.search(search) #self.でクラスメソッドとしている
     if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
       User.where(['family_name LIKE ? OR first_name LIKE ?', "%#{search}%" ,"%#{search}%"])
     else
       User.all #全て表示。
     end
    end

	def total_price
		cart_items = CartItem.where(user_id: id)
		cart_items.to_a.sum{|cart_item|cart_item.items_price}
	end

	def add_item(item_id)

		current_item = cart_items.find_by_item_id(item_id)

		if  current_item
			current_item.sheet += @current_item.sheet.to_i
		else
			current_item = cart_items.build(item_id: item_id)
		end
		current_item

	end



end

develop/app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  include DisplayAdminHeader

before_action :authenticate_admin!
  def index

  	@orders = Order.all
  	@orders = Order.page(params[:page]).per(20).order(id: "DESC")

  end

  def show
  	@order = Order.find(params[:id])
    @order_items = @order.order_items
    # @order_items = OrderItem.includes(:item)
    @user = @order.user
    # @user = User.includes(:address)
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.save
      flash[:notice] = "You have creatad delivery status successfully."
      redirect_to admins_order_path(@order)
    end
  end

  private
    def order_params
        params.require(:order).permit(:delivery_status)
    end
end

develop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

        before_action :set_header
        before_action :configure_permitted_parameters, if: :devise_controller?

	    protected

	    def configure_permitted_parameters
		  devise_parameter_sanitizer.permit(:sign_up, keys: [:address_id, :family_name, :first_name, :kana_family_name, :kana_first_name, :phone_number, :is_deleted])
	    end
	    
end

develop/app/controllers/top_controller.rb
class TopController < ApplicationController

  include DisplayUserHeader

  def top
  end

end

develop/app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController

  include DisplayUserHeader



  def new

    @user = current_user
    @addresses = @user.addresses.all
    @current_address = @user.addresses.first
    if @current_address
    @order = Order.new
    @order_items = @order.order_items.build
    @user = current_user
    else
    redirect_to new_users_address_path
  end
  end


  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @cart_items = CartItem.where(user_id: current_user.id)
    @cart_items.each do |cart_item|
      @item = cart_item.item
      if @item.stock_quantity >= cart_item.sheet
        @item.decrement!(:stock_quantity, cart_item.sheet.to_i)
        cart_item.destroy
      else
        redirect_to users_carts_path
      end
    end
      @order.delivery_status = 0
      @ad_info = Address.find_by(address: @order.address)
      @order.post_number = @ad_info.post_number
      @order.family_name = @ad_info.family_name
      @order.first_name = @ad_info.first_name
      @order.phone_number = @ad_info.phone_number
      @order.save
      flash[:notice] = "購入ありがとうございました。カートは空です。"
      redirect_to users_user_path(current_user)
  end


private
 def order_params
    params.require(:order).permit(:user_id, :payment_method, :delivery_status, :address, :post_number, :family_name, :first_name, :phone_number, :total_price, :shipping_fee,
    :amount, order_items_attributes: [:id, :item_id, :sheet, :price, :_destroy])
end

end

develop/app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

develop/app/helpers/application_helper.rb
module ApplicationHelper
end

develop/app/helpers/top_helper.rb
module TopHelper
end

develop/app/helpers/users/carts_helper.rb
module Users::CartsHelper
end

develop/app/helpers/users/items_helper.rb

module Users::ItemsHelper

  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end


end

develop/app/helpers/users/orders_helper.rb
module Users::OrdersHelper
end

develop/app/helpers/users/users_helper.rb
module Users::UsersHelper
end

develop/app/helpers/users_helper.rb
module UsersHelper
end

develop/app/views/admins/orders/index.html.erb
<body>
  <h2>購入履歴</h2>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h4>
      <table class="table table-striped">
        <% @orders.each do |order| %>
        <tbody>
         <tr>
           <td>
            <%= link_to admins_user_path(order.user.id) do %>
            <%= order.user.family_name %>
            <%= order.user.first_name %>
            <% end %>
           </td>
           <td>
            <%= order[:created_at].strftime("%Y-%m-%d　%H:%M")  %>
           </td>
           <td>
            <%= order.delivery_status %>
           </td>
           <td>
            <%= link_to "詳細画面へ",admins_order_path(order.id), class: "btn-sm btn-info" %>
           </td>
         </tr>
        </tbody>
        <% end %>
      </table>
    </h4>
    <%= paginate @orders %>
    </div>
  </div>
  

</div>
</body>

develop/app/views/admins/orders/show.html.erb
<div class='container'>
  <div class='row'>
  	<h2>注文管理</h2>
    <%=@order[:created_at].strftime("%Y-%m-%d　%H:%M")  %>
    <h3><%= @order.delivery_status %></h3>
    <%= form_for(@order, url: admins_order_path) do |f| %>
      <%= f.select :delivery_status, Order.delivery_statuses.keys.to_a,{} %>
      <%= f.submit '配送ステータス変更' %>
    <% end %>

    <div class='col-xs-12'>
       <table class='table table-striped'>
          <thead>
            <tr>
              <th></th>
              <th>商品名</th>
              <th>アーティスト名</th>
              <th>価格（税込）</th>
              <th>個数</th>
              <th>小計（税込）</th>
            </tr>
          </thead>
          <tbody>
　　　　　　　<% @order_items.each do |order_item| %>
              <tr>
                
	              <td>
                  <%= link_to admins_item_path(order_item.item.id) do %>
                  <%= attachment_image_tag order_item.item, :jacket_image,size: '100x100', fallback: "no_image.jpg" %>
                </td>
                <% end %>
                <td>
                  <%= link_to admins_item_path(order_item.item.id) do %>
                  <%= order_item.item.product_name %>
                  <% end %>
                  </td>
                <td><%= order_item.item.artist.artist_name %></td>
                <td><%= number_with_delimiter((order_item.price*1.08).round).to_s %>円</td>
                <td><%= order_item.sheet %></td>
                <td><%= number_with_delimiter((order_item.price*1.08*order_item.sheet).round).to_s %>円</td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class='col-xs-12'>
     <hr>
     <b class="text-right"><dl class="dl-horizontal"><dt>商品合計</dt><dd><%= number_with_delimiter(@order.total_price.round).to_s %>円</dd></dl></b>
     <hr>
     <b class="text-right"><dl class="dl-horizontal"><dt>送料</dt><dd>500円</dd></dl></b>
     <hr>
     <b class="text-right"><dl class="dl-horizontal"><dt>ご請求総額</dt><dd><%= number_with_delimiter(@order.amount.round).to_s %>円</dd></dl></b>
     <hr>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12'>
      <hr>
      <h3>ユーザー情報</h3>
      <hr>
      <p>〒<%= @user.addresses.first.post_number.to_s %></p>
      <p><%= @user.addresses.first.address %></p>
      <br>
      <p>
        <%= link_to admins_user_path(@user.id) do %>
        <%= @user.addresses.first.family_name %><%= @user.addresses.first.first_name %>
          <% end %>
        </p>
      <p><%= @user.email %></p>
      <hr>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12'>
      <hr>
      <h3>配送先</h3>
      <hr>
      <p>〒<%= @order.post_number %></p>
      <p><%= @order.address %></p>
      <br>
      <p><%= @order.name %></p>
      <p><%= @order.payment_method %></p>
      <p><%= @order.phone_number %></p>
      <hr>
    </div>
  </div>
</div>

develop/app/views/admins/orders/update.html.erb
<h1>Admins::Orders#update</h1>
<p>Find me in app/views/admins/orders/update.html.erb</p>